language: python
python:
- '3.7'
- '3.8'
install:
- pip install ".[dev]"
script:
- flake8
- pytest
deploy:
  provider: pypi
  username: __token__
  password:
    secure: izqvuJ4yYi8g1DASyNhvuyUwuStz/Hs+o+jeZrBqXJvysshQmmLZlNFljhHbirpEFo81FqAJV0pCsnPivnHVGj72uJjy5oHTaBBeED1GtEl34+GvTO5HwUY9lQjbmQDStHoz1haTd1HESSByY/0uXkrjYiRGaz9cB6dx5vSHT9ZmZIn29n8seSSCAuc0Fjw4NGIkAvpCpo2g26VZBtuLCf00PgbYuSFbAo6ML6leygai+dReoiVMMzgiuMFn2GTG9FnmtCvSQZWU+JWGOY3ztYS6Hv8mYJ9HsMEL0HUuT1FbsCSZPbCeK4fnLavmBUTBwTLNHaxsx7o7qvL12XrkOjPSVlkQxuu0RNnTXpA08kFqCl48VnlqWyEw0RqIsEIgR3AKdA4/ravnELhgDm5y/PGiVb7NkixKd0ScnL/97fh2DLmhpBO1I/4yCC8BABVizL3GEtEnucoQ+qB7LcYgb6OYApKhXfqgyohkqakHdaK/hH3PHAiBYMuyfqXjdyWZIBbOk4C00VMYiAsoyCK/bJdcacr+DlKIbAQ19BHoSQ6p6rqxdfIQfURiNuogt6zdfh+OkNo/RUnWT06JsLFai7CtxUzv6QwZb241B2vDE8PFTHb2hJ74f0mj1guuMVkAfIvBRSxkxkWmqPoayyR8nso9nOtgf6TAaKoUmGBvbto=
  on:
    tags: true
    branch: master
    python: 3.8
