language: python
python:
- '3.7'
- '3.8'
install:
- pip install ".[dev]"
script:
- flake8
- pytest
deploy:
  provider: pypi
  username: pypi-AgEIcHlwaS5vcmcCJDI2MTBjYWRlLWVhNjktNGRjZS04ZmViLTg1YTQ3YWExNDU0ZgACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgFZaIEkcNYtU03STuRYpnOkwGIp082KYIfINEoVEG66U
  password:
    secure: kjKU2lyvRAMOvmmPS3LO8oWdqpJ9J7Kz5QKyUAcBietQW4HLvJkQVevZbgCtMWXA7Deai8ONMLpXcRqWYNGNYuPTBS5U2cd0Z0ZUZLqZy/JVINh1QF+rbq+cFOm9A++ulN/XJtdEEgjC+wktSlKjA4DHgrORcH+EVkchDM3zESl1rSe05kPJsrHq/FjVaOotCD73sql3ax4AsqwfR2P1bs3vJe7fjrL+2BguSEQniAjzBMWDg13JDwAJASjEHwh0kJa9U0nKYF1b8s3R4wBMjtfX57tEYeYrpoCpUgfAG77E8yzC6oej85sOZ5K/f2Flp2eCQog6OoAoGhu4b2zoi7RHznRdoy7fnOCwFbP36ABrJx4xXtRX32qKT7Rb0dpCeq8Y9MzsKiiusc1/3Boh9CmKL18EjEZiZxA/y7g7nV6pWsY9VRmyJkkzoOU5o5N2n61vK3ZHeDRA5hF7KonewdfLHTF4gku3S4s13CvLW4QnONbpZ4litF79tej817Sjph1gCb/NCkC2AaBxogUVqPQQ27zEunghZmD9iKbucnj+2FFDTuDfT/PESFD3tt0Q3wNHWQoaJGuIG+T/j6u85g7NCYMgIrACMSSl4fX8VzOoxS2MJmgJgsyAiKZCAVzRzk87NQa/ipbh8jfjDh/RKFVgUs8eYMGYdZbDScGRIPo=
  on:
    tags: true
    branch: master
