#!/usr/bin/env python3

from pathlib import Path
import os
from datetime import date

GIT_HOOKS_DIR = Path(__file__).parent
PROJECT_DIR = GIT_HOOKS_DIR.parent.parent


def assert_tests_ran_after_modification(
    test_suite_name, tests_ts_path, *target_f_paths,
):
    if not tests_ts_path.exists():
        DNE = (
            f"{test_suite_name} -- {tests_ts_path} -- {target_f_paths[0]} -- "
            f"{test_suite_name} was never ran. Run the tests, commit changes,"
            f" and push again."
        )
        raise SystemExit(DNE)

    with open(tests_ts_path) as f:
        tests_ts = float(f.read().strip())

    latest_mod_ts = -1
    latest_mod_f = None
    for f_path in target_f_paths:
        stat = os.stat(str(f_path))
        f_mod_ts = stat.st_mtime
        if f_mod_ts > latest_mod_ts:
            latest_mod_ts = f_mod_ts
            latest_mod_f = f_path

    if latest_mod_ts > tests_ts:
        test_ts_date_str = date.fromtimestamp(tests_ts).strftime("%Y-%m-%d")
        last_mod_ts_date_str = date.fromtimestamp(latest_mod_ts).strftime(
            "%Y-%m-%d"
        )
        DNE = (
            f"\n{test_suite_name} was last ran on {test_ts_date_str}, but"
            f"\n{latest_mod_f} was modified on {last_mod_ts_date_str}."
            f"\nRun test, commit changes, and push again."
        )
        raise SystemExit(DNE)


IB_BROKER_TEST_TS_F_PATH = PROJECT_DIR / "test_logs" / "test_ib_broker_ts.log"
IB_BROKER_F_PATH = PROJECT_DIR / "algotradepy" / "brokers" / "ib_broker.py"
assert_tests_ran_after_modification(
    "ib_broker_tests", IB_BROKER_TEST_TS_F_PATH, IB_BROKER_F_PATH,
)

IB_CONNECTOR_TEST_TS_F_PATH = (
    PROJECT_DIR / "test_logs" / "test_ib_connector_ts.log"
)
IB_CONNECTOR_F_PATH = (
    PROJECT_DIR / "algotradepy" / "connectors" / "ib_connector.py"
)
assert_tests_ran_after_modification(
    "ib_connector_tests", IB_CONNECTOR_TEST_TS_F_PATH, IB_CONNECTOR_F_PATH,
)
